"use client";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { useFetchMovie } from "../utiles/MovieFetch";
import MyCarousel from "../components/myCarousel";
import ListOfMovies from "../components/ListOfMovies";
import SearchBar from "../components/SearchBar";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main>
        <SearchBar />
       <MyCarousel />
       <ListOfMovies />
      </main>
    </>
  );
}
